orb:
  labels:
    environment: lab
    color: red
  config_manager:
    active: git
    sources:
      git:
        url: "https://github.com/richbibby/netbox-discovery-agent-policies"
        schedule: "* * * * *"  # Check for updates every minute
        branch: main
  backends:
    network_discovery:
    common:
      diode:
        target: grpc://webinar.netboxlabs.tech:8080/diode
        api_key: "${DIODE_API_KEY}"
        agent_name: agent01